imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

monolog:
    handlers:
        main:
            type: stream
            path: 'php://stderr'
            level: debug